### ISSUE TITLE
Limited to minSdkVersion 15

### ISSUE THREAD

**Issue by johnjohndoe** [marvinlabs/android-floatinglabel-widgets#20]
I added [version 1.5.0 of the library](https://github.com/marvinlabs/android-floatinglabel-widgets/tree/1.5.0) to an application project which defines `minSdkVersion 9`. When I compile the project the following error occurs:

> Error:Execution failed for task ':app:processDebugManifest'.
> Manifest merger failed : uses-sdk:minSdkVersion 9 cannot be smaller than version 15 declared in library /home/user/projects/MyApp/app/build/intermediates/exploded-aar/com.marvinlabs/android-floatinglabel-widgets/1.5.0/AndroidManifest.xml

What is the reason you [declared `minSdkVersion 15`](https://github.com/marvinlabs/android-floatinglabel-widgets/blob/1.5.0/gradle.properties)?
Can you backport the library?

---

Further, can you please explicitly state the **minSdkVersion** in the `README.md` so people do not spent time trying to integrate it when they target a lower SDK version?

**Comment by vpratfr** [comment]
Fixed by documenting requirements. Feel free to submit a PR for older API support.
