### ISSUE TITLE
Disable/Enable widgets programmatically

### ISSUE THREAD

**Issue by dsdebastiani** [marvinlabs/android-floatinglabel-widgets#21]
I have two ItemPickers on my layout, and I need insert items in picker2 after the user select a item in picker1. When the picker1 was not selected yet, I'd like to disable picker2.

I've tried `myPicker2.setEnabled(false)`, `myPicker2.setActived(false)` and `myPicker2.setClickable(false)` but nothing works. The problem is, when picker2 is empty and is clicked, the app crash:
```
java.lang.RuntimeException: StringPickerDialogFragment needs some items to pick from
```
I wouldn't like to insert a empty item on picker2. Is there a way to disable ItemPickers instead?

**Comment by vpratfr** [comment]
Closing, I have added a sample in the demo about how to handle this case. 
Proper way to do it is to add empty list and check before showing the fragment (we don't want to show an empty fragment)
