### ISSUE TITLE
NPE with FloatingLabelAutoCompleteTextView and AppCompat 22.1.1 on API 21+ 

### ISSUE THREAD

**Issue by oneEyedOdin** [marvinlabs/android-floatinglabel-widgets#32]
When using this library with AppCompat there is a null pointer exception which occurs
when running on API 21+.  The FloatingLabelAutoCompleteTextView's AutoCompleteTextView input is
injected as an AppCompatAutoCompleteTextView by the app compat library.  When    
```
inputWidget.setDropDownBackgroundResource(popupBackground)
```
is called, AppCompatAutoCompleteTextView tries to get the drawable from it's internal TintManager.  The TintManager is not initialized when running on 21+ because of the ```TintManager.SHOULD_BE_USED``` is false on 21+. [(See TintManager.java)](https://github.com/android/platform_frameworks_support/blob/master/v7/appcompat/src/android/support/v7/internal/widget/TintManager.java) (I haven't found the source for AppCompatAutoCompleteTextView online anywhere to link.)

My workaround for now is to change     
```java
inputWidget.setDropDownBackgroundResource(popupBackground); //FloatingLabelAutoCompleteTextView.java:90
```
to
```java
inputWidget.setDropDownBackgroundDrawable(getContext().getDrawable(popupBackground)); //FloatingLabelAutoCompleteTextView.java:90
```

I want to verify that this is an AppCompat issue and not a FloatingLabelWidget issue and see if anyone has a better workaround.

**Comment by oneEyedOdin** [comment]
The full workaround actually needs to be the following, since Context.getDrawable() wasn't added until API 21.

```
if(Build.VERSION.SDK_INT < Build.VERSION_CODES.LOLLIPOP) {
     inputWidget.setDropDownBackgroundResource(popupBackground);
}
else {
    inputWidget.setDropDownBackgroundDrawable(getContext().getDrawable(popupBackground));
}
```

**Comment by vpratfr** [comment]
Hi,

Thanks for the bug report and correction. Could you submit a pull request against the develop branch?
